### ISSUE TITLE
Allow HTML in questions

### ISSUE THREAD

**Issue by elearningdave** [csev/gift2qti#4]
We are trying to embed pictures into quiz questions, using the <img> tag (images have absolute paths to our web server). How do we modify the code to accept this? I'm guess it's early on in the make_qti.php script, but not sure exactly which lines need an if statement adding.

**Comment by csev** [comment]
What happens when you just put the anchor tag <a in an html question?

**Comment by elearningdave** [comment]
If you mean a proper hyperlink (e.g. a link to google UK), I get the following HTML (c/p from canvas' editor):

<p>___________ __________ means a cistern provided with valve or device for controlling the discharge of the stored water into a water closet pan or urinal. Complete the missing words. &lt;img src="https://imageurl.jpg" /&gt; &lt;a href="https://www.google.co.uk"&gt;Google UK&lt;/a&gt;</p>

**Comment by elearningdave** [comment]
For the record, I'm not putting any <p> tags in there. Raw question from the GIFT file...
::Q1 MC::___________  __________ means a cistern provided with valve or device for controlling the discharge of the stored water into a water closet pan or urinal. Complete the missing words. <img src="https://imgurl.jpg" /> <a href="https://www.google.co.uk">Google UK</a> {
=Flushing cistern
~Feed and Expansion Cistern
~Storage Cistern
~Backflow cistern
}

**Comment by elearningdave** [comment]
Argh because I left the raw <a> tag in there, it has tried to do something clever in the github rich editor

**Comment by csev** [comment]
I just made this:

    ::Q5::[html]Hello <b>world</b> 
    <img src="https://www.dr-chuck.com/csev_ian_dolphin_small.jpg">.
    { =Right =Correct ~Wrong ~Incorrect }

It worked.

**Comment by elearningdave** [comment]
That fixed it,thanks. Couldn't find it in any documentation (even moodle doc's official latest version).
I have another question their documentation doesn't answer, but will put this in a new 'issue'.

**Comment by csev** [comment]
Yup - I know of no other documentation.  It is what I read when working on the code.
