### ISSUE TITLE
Overall Feedback option

### ISSUE THREAD

**Issue by elearningdave** [csev/gift2qti#5]
We want to add feedback for each question, regardless of what they answered (revision signposting).
Is there a way of doing this in GIFT, as the moodle doc for the latest version only offers the ability to do per-answer feedback (which I will do if necessary, but it would be neater to give it to them once).

**Comment by csev** [comment]
I don't want to wander off into my own format.  This is a simple tool whose goal is to be as close to the GIFT spec as it can be.  Extensions should be vetted through the owners of GIFT.  I am absolutely not an expert.   If I added an extension - I would likely break something else without knowing it.
